---
volumes:
  jenkins_home:
    driver: local

networks:
  jenkins:
    external: true
    
      
services:
  
  master:
    image: jenkins/jenkins:2.440.3-lts-jdk17
    container_name: master
    hostname: master
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    expose: 
      - "50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
        - jenkins
        
  agent1: 
    image: jenkins/ssh-agent:jdk21
    container_name: agent1
    hostname: agent1
    restart: unless-stopped
    expose: 
      - "22"
      - "50000"
    networks:
      - jenkins

  agent2: 
    image: jenkins/ssh-agent:jdk21
    container_name: agent2
    hostname: agent2
    restart: unless-stopped
    expose: 
      - "22"
      - "50000"
    networks:
      - jenkins

